/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Core.AddCompany;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class AddCompForm extends javax.swing.JFrame {

    /**
     * Creates new form compJFrame
     */
    public AddCompForm() {
        this.setTitle("Placement Database - Add Company");
        initComponents();
        SUBMITBUTTON.setEnabled(true);
        updateBtn.setEnabled(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        complabel = new javax.swing.JLabel();
        compnamelabel = new javax.swing.JLabel();
        aggregatelabel = new javax.swing.JLabel();
        branchlabel = new javax.swing.JLabel();
        packagelabel = new javax.swing.JLabel();
        locationlabel = new javax.swing.JLabel();
        contlabel = new javax.swing.JLabel();
        SUBMITBUTTON = new javax.swing.JButton();
        RESETBUTTON = new javax.swing.JButton();
        compnametext = new javax.swing.JTextField();
        aggregatetext = new javax.swing.JTextField();
        packagetext = new javax.swing.JTextField();
        loctext = new javax.swing.JTextField();
        conttext = new javax.swing.JTextField();
        branchCombo = new javax.swing.JComboBox();
        updateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        complabel.setText("COMPANY REGISTRATION FORM");

        compnamelabel.setText("Company Name:");

        aggregatelabel.setText("Aggregate cut-off:");

        branchlabel.setText("Qualified Branches:");

        packagelabel.setText("Package:");

        locationlabel.setText("Location:");

        contlabel.setText("Contact No.:");

        SUBMITBUTTON.setText("SUBMIT");
        SUBMITBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITBUTTONActionPerformed(evt);
            }
        });

        RESETBUTTON.setText("RESET");
        RESETBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETBUTTONActionPerformed(evt);
            }
        });

        aggregatetext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aggregatetextKeyTyped(evt);
            }
        });

        packagetext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                packagetextKeyTyped(evt);
            }
        });

        conttext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                conttextKeyTyped(evt);
            }
        });

        branchCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer Science", "Electronics & communication", "Information Science", "Telecommunication", "Biotechnology", "Mechanical", "Civil", "Electrical & Electronics" }));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(complabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aggregatelabel)
                                .addGap(50, 50, 50)
                                .addComponent(aggregatetext, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(compnamelabel)
                                .addGap(62, 62, 62)
                                .addComponent(compnametext, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(updateBtn)
                                    .addGap(18, 18, 18)
                                    .addComponent(SUBMITBUTTON)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(RESETBUTTON))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(branchlabel)
                                        .addComponent(packagelabel)
                                        .addComponent(locationlabel)
                                        .addComponent(contlabel))
                                    .addGap(48, 48, 48)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(loctext)
                                        .addComponent(packagetext)
                                        .addComponent(conttext)
                                        .addComponent(branchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(complabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compnamelabel)
                    .addComponent(compnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aggregatelabel)
                    .addComponent(aggregatetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branchlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packagetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SUBMITBUTTON)
                    .addComponent(RESETBUTTON)
                    .addComponent(updateBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SUBMITBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITBUTTONActionPerformed

        Core.AddCompany addCompanyOBJ = new AddCompany();
        String cname = compnametext.getText();
        String aggregate = aggregatetext.getText();
        String cbranch = (String) branchCombo.getSelectedItem();
        String salpackage = packagetext.getText();
        String location = loctext.getText();
        String cphoneno = conttext.getText();

        if (cname.equals("") || aggregate.equals("") || cbranch.equals("") || salpackage.equals("") || location.equals("") | cphoneno.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill all the details", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Boolean res = addCompanyOBJ.insert(cname, aggregate, cbranch, cphoneno, location, salpackage);
            if (res) {
                JOptionPane.showMessageDialog(this, "Company Inserted Successfully", "success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Could not insert record", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_SUBMITBUTTONActionPerformed

    public void update(String name, String branch, String aggrigate, String cphone, String clocation, String salpackage) {

        updateBtn.setEnabled(true);
        SUBMITBUTTON.setEnabled(false);
        compnametext.setText(name);
        aggregatetext.setText(aggrigate);
        packagetext.setText(salpackage);
        loctext.setText(clocation);
        conttext.setText(cphone);
        branchCombo.setSelectedItem(branch);
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        new MainForm().setVisible(true);

    }//GEN-LAST:event_formWindowClosing

    private void aggregatetextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aggregatetextKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_PERIOD))) {
            evt.consume();
        }
    }//GEN-LAST:event_aggregatetextKeyTyped

    private void packagetextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_packagetextKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_PERIOD) || (c == KeyEvent.VK_COMMA))) {
            evt.consume();
        }
    }//GEN-LAST:event_packagetextKeyTyped

    private void conttextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conttextKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_conttextKeyTyped

    private void RESETBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETBUTTONActionPerformed
        compnametext.setText("");
        aggregatetext.setText("");
        packagetext.setText("");
        loctext.setText("");
        conttext.setText("");
    }//GEN-LAST:event_RESETBUTTONActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        Core.AddCompany addCompanyOBJ = new AddCompany();

        String cname = compnametext.getText();
        String aggregate = aggregatetext.getText();
        String cbranch = (String) branchCombo.getSelectedItem();
        String salpackage = packagetext.getText();
        String location = loctext.getText();
        String cphoneno = conttext.getText();

        if (cname.equals("") || aggregate.equals("") || cbranch.equals("") || salpackage.equals("") || location.equals("") | cphoneno.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill all the details", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Boolean res = addCompanyOBJ.update(cname, aggregate, cbranch, cphoneno, location, salpackage);
            if (res) {
                JOptionPane.showMessageDialog(this, "Company updated Successfully", "success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Could not update company record", "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCompForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCompForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCompForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCompForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCompForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RESETBUTTON;
    private javax.swing.JButton SUBMITBUTTON;
    private javax.swing.JLabel aggregatelabel;
    private javax.swing.JTextField aggregatetext;
    private javax.swing.JComboBox branchCombo;
    private javax.swing.JLabel branchlabel;
    private javax.swing.JLabel complabel;
    private javax.swing.JLabel compnamelabel;
    private javax.swing.JTextField compnametext;
    private javax.swing.JLabel contlabel;
    private javax.swing.JTextField conttext;
    private javax.swing.JLabel locationlabel;
    private javax.swing.JTextField loctext;
    private javax.swing.JLabel packagelabel;
    private javax.swing.JTextField packagetext;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
