/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Core.AddStudent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class AddStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public AddStudentForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Placement Database - Add Students");
        UpdateBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resetbutton = new javax.swing.JButton();
        emailtext = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        yeartext = new javax.swing.JComboBox();
        contacttext = new javax.swing.JTextField();
        betext = new javax.swing.JTextField();
        puctext = new javax.swing.JTextField();
        sslctext = new javax.swing.JTextField();
        yytext = new javax.swing.JComboBox();
        mmtext = new javax.swing.JComboBox();
        ddtext = new javax.swing.JComboBox();
        gendertext = new javax.swing.JComboBox();
        branchtext = new javax.swing.JComboBox();
        nametext = new javax.swing.JTextField();
        fathertext = new javax.swing.JTextField();
        namelabel = new javax.swing.JLabel();
        idtext = new javax.swing.JTextField();
        emaillabel = new javax.swing.JLabel();
        contactlabel = new javax.swing.JLabel();
        yearlabel = new javax.swing.JLabel();
        belabel = new javax.swing.JLabel();
        genderlabel = new javax.swing.JLabel();
        puclabel = new javax.swing.JLabel();
        sslclabel = new javax.swing.JLabel();
        doblabel = new javax.swing.JLabel();
        branchlabel = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        fatherlabel = new javax.swing.JLabel();
        UpdateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("STUDENT REGISTRATION");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("STUDENT REGISTRATION"));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentHidden(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resetbutton.setText("RESET");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));
        jPanel1.add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 160, -1));

        submitbutton.setText("SUBMIT");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(submitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, -1, -1));

        yeartext.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jPanel1.add(yeartext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 64, -1));

        contacttext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contacttextKeyTyped(evt);
            }
        });
        jPanel1.add(contacttext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 160, -1));

        betext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                betextKeyTyped(evt);
            }
        });
        jPanel1.add(betext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 55, -1));

        puctext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                puctextKeyTyped(evt);
            }
        });
        jPanel1.add(puctext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 55, -1));

        sslctext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sslctextKeyTyped(evt);
            }
        });
        jPanel1.add(sslctext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 55, -1));

        yytext.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000" }));
        jPanel1.add(yytext, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 70, -1));

        mmtext.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(mmtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 50, -1));

        ddtext.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(ddtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 50, -1));

        gendertext.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        gendertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gendertextActionPerformed(evt);
            }
        });
        jPanel1.add(gendertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        branchtext.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer Science", "Electronics & communication", "Information Science", "Telecommunication", "Biotechnology", "Mechanical", "Civil", "Electrical & Electronics" }));
        branchtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchtextActionPerformed(evt);
            }
        });
        jPanel1.add(branchtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        nametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextActionPerformed(evt);
            }
        });
        nametext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nametextKeyTyped(evt);
            }
        });
        jPanel1.add(nametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 160, -1));

        fathertext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fathertextKeyTyped(evt);
            }
        });
        jPanel1.add(fathertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, -1));

        namelabel.setText("Name:");
        jPanel1.add(namelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 55, -1));
        jPanel1.add(idtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 160, -1));

        emaillabel.setText("email:");
        jPanel1.add(emaillabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        contactlabel.setText("contact No.:");
        jPanel1.add(contactlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 69, -1));

        yearlabel.setText("Year of Passing:");
        jPanel1.add(yearlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 22));

        belabel.setText("B.E aggregate:");
        jPanel1.add(belabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        genderlabel.setText("Gender:");
        jPanel1.add(genderlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        puclabel.setText("12th percent:");
        jPanel1.add(puclabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        sslclabel.setText("SSLC percent:");
        jPanel1.add(sslclabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        doblabel.setText("DOB:");
        jPanel1.add(doblabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 23));

        branchlabel.setText("Branch:");
        jPanel1.add(branchlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        idlabel.setText("student USN :");
        jPanel1.add(idlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        fatherlabel.setText("Father's name:");
        jPanel1.add(fatherlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 34));

        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametextActionPerformed

    private void branchtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchtextActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        // TODO add your handling code here:
        nametext.setText("");
        idtext.setText("");
        fathertext.setText("");
        sslctext.setText("");
        puctext.setText("");
        betext.setText("");
        contacttext.setText("");
        emailtext.setText("");
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        Core.AddStudent addStudentOBJ = new AddStudent();

        String name = nametext.getText();
        String usn = idtext.getText();
        String fatherName = fathertext.getText();
        String sslc = sslctext.getText();
        String puc = puctext.getText();
        String be = betext.getText();
        String contact = contacttext.getText();
        String email = emailtext.getText();
        String dob = (String) ddtext.getSelectedItem() + "/" + mmtext.getSelectedItem() + "/" + yytext.getSelectedItem();
        String gender = (String) gendertext.getSelectedItem();
        String branch = (String) branchtext.getSelectedItem();
        String yop = (String) yeartext.getSelectedItem();


        if (!usn.matches("[0-4][a-zA-Z][a-zA-Z][0-9][0-9][a-zA-Z][a-zA-Z][0-9][0-9][0-9]")) {
            JOptionPane.showMessageDialog(this, "Invalid USN format", "Error", JOptionPane.INFORMATION_MESSAGE);

        }
        if (name.equals("") || usn.equals("") || fatherName.equals("") || sslc.equals("") || puc.equals("") || be.equals("") || contact.equals("") || email.equals("") || dob.equals("") || gender.equals("") || branch.equals("") || yop.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill all the details", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Boolean res = addStudentOBJ.insert(name, usn.toLowerCase(), gender, fatherName, branch, dob, sslc, puc, be, yop, contact, email);
            if (res) {
                nametext.setText("");
                idtext.setText("");
                fathertext.setText("");
                sslctext.setText("");
                puctext.setText("");
                betext.setText("");
                contacttext.setText("");
                emailtext.setText("");
                JOptionPane.showMessageDialog(this, "Student Inserted Successfully", "success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Could not insert record", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submitbuttonActionPerformed

    public void update(String usn, String name, String gender, String fname, String dob, String branch, String sslc, String puc, String be, String phone, String email, String yop) {
        UpdateBtn.setEnabled(true);
        submitbutton.setEnabled(false);
        idtext.setEditable(false);

        nametext.setText(name);
        idtext.setText(usn);
        fathertext.setText(fname);
        sslctext.setText(sslc);
        puctext.setText(puc);
        betext.setText(be);
        contacttext.setText(phone);
        emailtext.setText(email);
        yeartext.setSelectedItem(yop);
        gendertext.setSelectedItem(gender);
        branchtext.setSelectedItem(branch);

        String[] dmy = dob.split("/");
        ddtext.setSelectedItem(dmy[0]);
        mmtext.setSelectedItem(dmy[1]);
        yytext.setSelectedItem(dmy[2]);



    }
    private void jPanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentHidden
    }//GEN-LAST:event_jPanel1ComponentHidden

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        new MainForm().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void gendertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gendertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gendertextActionPerformed

    private void nametextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nametextKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isLetter(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SPACE))) {
            evt.consume();
        }
    }//GEN-LAST:event_nametextKeyTyped

    private void fathertextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fathertextKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isLetter(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SPACE))) {
            evt.consume();
        }
    }//GEN-LAST:event_fathertextKeyTyped

    private void sslctextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sslctextKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_PERIOD))) {
            evt.consume();
        }
    }//GEN-LAST:event_sslctextKeyTyped

    private void puctextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_puctextKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_PERIOD))) {
            evt.consume();
        }
    }//GEN-LAST:event_puctextKeyTyped

    private void betextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_betextKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_PERIOD))) {
            evt.consume();
        }
    }//GEN-LAST:event_betextKeyTyped

    private void contacttextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contacttextKeyTyped
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_contacttextKeyTyped

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        Core.AddStudent addStudentOBJ = new AddStudent();

        String name = nametext.getText();
        String usn = idtext.getText();
        String fatherName = fathertext.getText();
        String sslc = sslctext.getText();
        String puc = puctext.getText();
        String be = betext.getText();
        String contact = contacttext.getText();
        String email = emailtext.getText();
        String dob = (String) ddtext.getSelectedItem() + "/" + mmtext.getSelectedItem() + "/" + yytext.getSelectedItem();
        String gender = (String) gendertext.getSelectedItem();
        String branch = (String) branchtext.getSelectedItem();
        String yop = (String) yeartext.getSelectedItem();


        if (!usn.matches("[0-4][a-zA-Z][a-zA-Z][0-9][0-9][a-zA-Z][a-zA-Z][0-9][0-9][0-9]")) {
            JOptionPane.showMessageDialog(this, "Invalid USN format", "Error", JOptionPane.INFORMATION_MESSAGE);

        }
        if (name.equals("") || usn.equals("") || fatherName.equals("") || sslc.equals("") || puc.equals("") || be.equals("") || contact.equals("") || email.equals("") || dob.equals("") || gender.equals("") || branch.equals("") || yop.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill all the details", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Boolean res = addStudentOBJ.update(name, usn.toLowerCase(), gender, fatherName, branch, dob, sslc, puc, be, yop, contact, email);
            if (res) {
                nametext.setText("");
                idtext.setText("");
                fathertext.setText("");
                sslctext.setText("");
                puctext.setText("");
                betext.setText("");
                contacttext.setText("");
                emailtext.setText("");
                JOptionPane.showMessageDialog(this, "Student Updated Successfully", "success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Could not Update record", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddStudentForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel belabel;
    private javax.swing.JTextField betext;
    private javax.swing.JLabel branchlabel;
    private javax.swing.JComboBox branchtext;
    private javax.swing.JLabel contactlabel;
    private javax.swing.JTextField contacttext;
    private javax.swing.JComboBox ddtext;
    private javax.swing.JLabel doblabel;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JTextField emailtext;
    private javax.swing.JLabel fatherlabel;
    private javax.swing.JTextField fathertext;
    private javax.swing.JLabel genderlabel;
    private javax.swing.JComboBox gendertext;
    private javax.swing.JLabel idlabel;
    private javax.swing.JTextField idtext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox mmtext;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField nametext;
    private javax.swing.JLabel puclabel;
    private javax.swing.JTextField puctext;
    private javax.swing.JButton resetbutton;
    private javax.swing.JLabel sslclabel;
    private javax.swing.JTextField sslctext;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel yearlabel;
    private javax.swing.JComboBox yeartext;
    private javax.swing.JComboBox yytext;
    // End of variables declaration//GEN-END:variables
}
