/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Core.DBConnect;
import Core.IDBConnect;
import Core.Init;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class MainForm extends javax.swing.JFrame implements IDBConnect {

    public String user = null;
    public static String type = null;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setTitle("Placement Database");
        setLocationRelativeTo(null);
        ViewRegComp.setVisible(false);
    }

    MainForm(String username, String type) {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Placement Database");
        user = username;
        MainForm.type = type;
        ViewRegComp.setVisible(false);
        //changing the view based on admin or user.

        if (!type.equals(ADMIN)) {
            AddStudMenu.setVisible(false);
            ViewStudents.setVisible(false);
            AddUserMenu.setVisible(false);
            AddCompany.setVisible(false);
            ViewRegComp.setVisible(true);
        } else {
            ViewRegComp.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AddStudMenu = new javax.swing.JMenuItem();
        ViewStudents = new javax.swing.JMenuItem();
        AddCompany = new javax.swing.JMenuItem();
        ViewCompMenu = new javax.swing.JMenuItem();
        ViewRegComp = new javax.swing.JMenuItem();
        logOutMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ChangePass = new javax.swing.JMenuItem();
        AddUserMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AboutUsMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("File");

        AddStudMenu.setText("Add Student");
        AddStudMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudMenuActionPerformed(evt);
            }
        });
        jMenu1.add(AddStudMenu);

        ViewStudents.setText("View Students");
        ViewStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStudentsActionPerformed(evt);
            }
        });
        jMenu1.add(ViewStudents);

        AddCompany.setText("Add Company");
        AddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCompanyActionPerformed(evt);
            }
        });
        jMenu1.add(AddCompany);

        ViewCompMenu.setText("View Company");
        ViewCompMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCompMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ViewCompMenu);

        ViewRegComp.setText("View Registered company");
        ViewRegComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRegCompActionPerformed(evt);
            }
        });
        jMenu1.add(ViewRegComp);

        logOutMenu.setText("Log out");
        logOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutMenuActionPerformed(evt);
            }
        });
        jMenu1.add(logOutMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        ChangePass.setText("Change Password");
        ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePassActionPerformed(evt);
            }
        });
        jMenu2.add(ChangePass);

        AddUserMenu.setText("Add User");
        AddUserMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserMenuActionPerformed(evt);
            }
        });
        jMenu2.add(AddUserMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        AboutUsMenu.setText("About us");
        AboutUsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutUsMenuActionPerformed(evt);
            }
        });
        jMenu3.add(AboutUsMenu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddStudMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudMenuActionPerformed
        this.setVisible(false);
        AddStudentForm ASF = new AddStudentForm();
        ASF.setVisible(true);
    }//GEN-LAST:event_AddStudMenuActionPerformed

    private void ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePassActionPerformed
        UpdatePassForm UPF = new UpdatePassForm(user,type);
        UPF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ChangePassActionPerformed

    private void ViewStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStudentsActionPerformed
        ViewStudentsForm VSFObj = new ViewStudentsForm();
        VSFObj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewStudentsActionPerformed

    private void AddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCompanyActionPerformed
        AddCompForm CJFObj = new AddCompForm();
        this.setVisible(false);
        CJFObj.setVisible(true);
    }//GEN-LAST:event_AddCompanyActionPerformed

    private void AddUserMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserMenuActionPerformed
        SignupForm SUFObj = new SignupForm(user, ADMIN);
        SUFObj.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_AddUserMenuActionPerformed

    private void ViewCompMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCompMenuActionPerformed
        ViewCompForm VCFObj = new ViewCompForm(user, type);
        VCFObj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewCompMenuActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit", "Exit ?", JOptionPane.OK_CANCEL_OPTION);
        if (x == 0) {
            try {
                DBConnect.connection.close();
            } catch (SQLException ex) {
                System.out.println("Cannot close connection");
            }
            System.exit(0);

        }
    }//GEN-LAST:event_formWindowClosing

    private void logOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutMenuActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to Log out", "Log out ?", JOptionPane.OK_CANCEL_OPTION);
        if (x == 0) {
            try {
                DBConnect.connection.close();
                this.dispose();
            } catch (SQLException ex) {
                System.out.println("Cannot close connection");
            }
            Init init = new Core.Init();


        }
    }//GEN-LAST:event_logOutMenuActionPerformed

    private void ViewRegCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRegCompActionPerformed
        ViewRegisteredStudForm VRSFObj = new ViewRegisteredStudForm(user);
        this.dispose();
        VRSFObj.setVisible(true);
    }//GEN-LAST:event_ViewRegCompActionPerformed

    private void AboutUsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutUsMenuActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_AboutUsMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutUsMenu;
    private javax.swing.JMenuItem AddCompany;
    private javax.swing.JMenuItem AddStudMenu;
    private javax.swing.JMenuItem AddUserMenu;
    private javax.swing.JMenuItem ChangePass;
    private javax.swing.JMenuItem ViewCompMenu;
    private javax.swing.JMenuItem ViewRegComp;
    private javax.swing.JMenuItem ViewStudents;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logOutMenu;
    // End of variables declaration//GEN-END:variables
}
