/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Core.IDBConnect;
import Core.SignUp;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class SignupForm extends javax.swing.JFrame implements IDBConnect {

    String userType = "user";
    String USN = null;
    String user = null;

    /**
     * Creates new form SignupForm
     */
    public SignupForm() {
        this.setTitle("Placement Database -  Sign Up");
        initComponents();
        setLocationRelativeTo(null);
        typeAdmin.setVisible(false);
        typeUser.setVisible(false);
        userTypeLabel.setVisible(false);
    }

    SignupForm(String user, String type) {
        initComponents();
        this.setTitle("Placement Database -  Sign Up");
        setLocationRelativeTo(null);
        userType = type;
        this.user = user;
        typeAdmin.setVisible(false);
        typeUser.setVisible(false);
        userTypeLabel.setVisible(false);
        if (userType.equals(ADMIN)) {
            typeAdmin.setVisible(true);
            typeUser.setVisible(true);
            userTypeLabel.setVisible(true);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        UsnText = new javax.swing.JTextField();
        SignUpbtn = new javax.swing.JButton();
        confirmText = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        userTypeLabel = new javax.swing.JLabel();
        typeUser = new javax.swing.JRadioButton();
        typeAdmin = new javax.swing.JRadioButton();
        passText = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        USNLabel = new javax.swing.JLabel();
        userText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));
        jPanel1.add(UsnText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 170, -1));

        SignUpbtn.setText("Sign up");
        SignUpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpbtnActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));
        jPanel1.add(confirmText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 174, -1));

        jLabel3.setText("Confirm Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        userTypeLabel.setText("User Type :");
        jPanel1.add(userTypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        typeButtonGroup.add(typeUser);
        typeUser.setSelected(true);
        typeUser.setText("User");
        typeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeUserActionPerformed(evt);
            }
        });
        jPanel1.add(typeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        typeButtonGroup.add(typeAdmin);
        typeAdmin.setText("Admin");
        typeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeAdminActionPerformed(evt);
            }
        });
        jPanel1.add(typeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));
        jPanel1.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 174, -1));

        jLabel2.setText("Password :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel1.setText("Username :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        USNLabel.setText("USN :");
        jPanel1.add(USNLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        jPanel1.add(userText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 174, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpbtnActionPerformed
        Core.SignUp SUObj = new SignUp();

        String username = userText.getText();
        String password = passText.getText();
        String confirmPass = confirmText.getText();
        boolean ok = false;

        String type = "user";



        if (username.equals("") || password.equals("") || confirmPass.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill all the details", "ERROR", JOptionPane.ERROR_MESSAGE);
            ok = false;
        } else {
            if (typeAdmin.isSelected()) {
                type = ADMIN;
                USN = ADMIN;
                ok = true;
            } else {
                type = "user";
                USN = UsnText.getText();
                if (USN.equals("")) {
                    JOptionPane.showMessageDialog(this, "Please fill all the details", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else if (!USN.matches("[0-4][a-zA-Z][a-zA-Z][0-9][0-9][a-zA-Z][a-zA-Z][0-9][0-9][0-9]")) {
                    JOptionPane.showMessageDialog(this, "Invalid USN format", "Error", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    ok = true;
                }
            }

            if (ok) {
                if (password.equals(confirmPass)) {
                    SUObj.insert(USN, username, password, type);
                } else {
                    JOptionPane.showMessageDialog(this, "Passwords donot match", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_SignUpbtnActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void typeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeAdminActionPerformed

        UsnText.setVisible(false);  //no usn field for ADMIN
        USNLabel.setVisible(false);

    }//GEN-LAST:event_typeAdminActionPerformed

    private void typeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeUserActionPerformed
        UsnText.setVisible(true);
        USNLabel.setVisible(true);
    }//GEN-LAST:event_typeUserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        UsnText.setText("");
        passText.setText("");
        confirmText.setText("");
        userText.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignUpbtn;
    private javax.swing.JLabel USNLabel;
    private javax.swing.JTextField UsnText;
    private javax.swing.JPasswordField confirmText;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passText;
    private javax.swing.JRadioButton typeAdmin;
    private javax.swing.ButtonGroup typeButtonGroup;
    private javax.swing.JRadioButton typeUser;
    private javax.swing.JTextField userText;
    private javax.swing.JLabel userTypeLabel;
    // End of variables declaration//GEN-END:variables
}
